displayName=Golem Crafting Never Lucky
author=Jezice
description=Shows a configurable Never lucky message when a configured Golem Crafting event is detected.
tags=golem,crafting,minigame,never,lucky
plugins=com.ospikachu.GolemCraftingNeverLuckyPlugin
version=
build=standard
